openapi: 3.0.0
info:
  title: Admin Management API
  version: 1.0.0
  description: API for managing admins, including creation, retrieval, update, and deletion.
servers:
  - url: "http://localhost:3000/api"
    description: API server

tags:
  - name: Admins
    description: Operations related to admin management

paths:
  /api/admins:
    post:
      tags:
        - Admins
      summary: Add a new admin
      description: Creates a new admin user with the provided details.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "John Doe"
                email:
                  type: string
                  example: "john.doe@example.com"
                phone:
                  type: string
                  example: "+1234567890"
                password:
                  type: string
                  example: "password123"
                photo:
                  type: string
                  format: binary
              required:
                - name
                - email
                - phone
                - password
      responses:
        "200":
          description: Admin created successfully
        "400":
          description: Bad request
        "409":
          description: Conflict, email already exists
        "500":
          description: Internal server error

    get:
      tags:
        - Admins
      summary: Retrieve all admins
      description: Retrieves a list of all admins.
      responses:
        "200":
          description: A list of admins
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
                    phone:
                      type: string
                    photo:
                      type: string
                    role:
                      type: integer
        "500":
          description: Internal server error

  /api/admins/{id}:
    get:
      tags:
        - Admins
      summary: Retrieve a specific admin
      description: Retrieves details of a specific admin by ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the admin to retrieve
          schema:
            type: string
      responses:
        "200":
          description: Admin details
          content:
            application/json:
              schema:
                type: object
                properties:
                  totp:
                    type: string
                  totp_qr:
                    type: string
        "400":
          description: Bad request, ID is required
        "404":
          description: Admin not found
        "500":
          description: Internal server error

    put:
      tags:
        - Admins
      summary: Update an admin
      description: Updates the details of a specific admin.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the admin to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "John Doe"
                email:
                  type: string
                  example: "john.doe@example.com"
                phone:
                  type: string
                  example: "+1234567890"
                photo:
                  type: string
                  format: binary
              required:
                - email
      responses:
        "200":
          description: Admin updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                  photo:
                    type: string
        "400":
          description: Bad request
        "404":
          description: Admin not found
        "500":
          description: Internal server error

    delete:
      tags:
        - Admins
      summary: Delete an admin
      description: Deletes a specific admin by ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the admin to delete
          schema:
            type: string
      responses:
        "200":
          description: Admin deleted successfully
        "400":
          description: Bad request, ID is required
        "404":
          description: Admin not found
        "500":
          description: Internal server error
