openapi: 3.0.0
info:
  title: Job Management API
  version: 1.0.0
  description: API for retrieving job execution details from AWS IoT.
tags:
  - name: Job
    description: Operations related to Jobs
paths:
  /api/job-details:
    post:
      summary: Retrieve job execution details
      description: Fetches job execution details using the provided job ARN.
      tags:
        - Job
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                arn:
                  type: string
                  description: The Amazon Resource Name (ARN) of the job. This is used to fetch job details.
              required:
                - arn
      responses:
        "200":
          description: Job execution details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
                    description: The ID of the job.
                  executions:
                    type: array
                    items:
                      type: object
                      properties:
                        executionId:
                          type: string
                          description: Unique identifier for the job execution.
                        status:
                          type: string
                          description: Status of the job execution.
                        timestamp:
                          type: string
                          format: date-time
                          description: Timestamp when the job execution was created.
        "400":
          description: Bad Request - ARN is required
        "500":
          description: Internal server error
