openapi: 3.0.0
info:
  title: Logging API
  version: 1.0.0
  description: API for retrieving log entries from the system.
tags:
  - name: Logs
    description: Operations related to Logs
paths:
  /api/logger/logs:
    get:
      summary: Retrieve all logs
      description: Fetches a list of all log entries stored in the database.
      tags:
        - Logs
      responses:
        "200":
          description: A list of log entries
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The unique identifier of the log entry.
                    timestamp:
                      type: string
                      format: date-time
                      description: The date and time when the log entry was created.
                    level:
                      type: string
                      description: The severity level of the log entry (e.g., INFO, WARN, ERROR).
                    message:
                      type: string
                      description: The actual log message.
                    details:
                      type: string
                      description: Additional details about the log entry.
                example:
                  - id: 1
                    timestamp: "2024-09-10T12:34:56Z"
                    level: INFO
                    message: "System started successfully"
                    details: "Additional details if any"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message describing what went wrong.
                example:
                  error: "Something went wrong"
